### ISSUE TITLE
No see ble devices in nordic lib

### ISSUE THREAD

**Issue by arstagaev** [wotosts/AndroidBleSample#1]
Thanks for sample!
List in the nordic activity empty but in this time rxble activity has many items in list.
Nordic don't work properly?

What do you think why did it happen?:)

**Comment by wotosts** [comment]
Hi, 
I fixed that issue! 
The issue occurred because the associated variable was null during the scan using the nordic library. 
plz pull and test it again. 

Thank you :)

**Comment by arstagaev** [comment]
wooooww. All works! :) Your sample of this libs a super understandable in all GitHub))

**Comment by arstagaev** [comment]
Where do you learn of Bluetooth Low Energy? Any source, repositories?

**Comment by wotosts** [comment]
I'm glad to be of help! 

I have referred to the **official sample and documents** of each libraries, and especially on **Android Developer site**. 
If you are new to developing BLE, I recommend you to read the BLE section of Android Developer.
